SELECT * FROM firstproj;

--1.what is the total revenue generated by male vs. female customers?
select gender,sum(purchase_amount)as revenue
from firstproj
group by gender

--2.which customers used a discount but still spent more than the average purchase amount?
select customer_id,purchase_amount from firstproj
where discount_applied='Yes' AND purchase_amount>=(select avg(purchase_amount) from firstproj)

--3.what are the top 5 products with the highest average review rating?
select top 5
item_purchased,round(avg(review_rating),2) as "average product rating" from firstproj
group by item_purchased
order by avg(review_rating) desc;

--4 compare the average purchase amout between standard and express shipping
select shipping_type ,avg(purchase_amount) from firstproj
where shipping_type in ('Standard','Express') --- it is written only to select those 2 types not all
group by shipping_type

--5.do subscribed customers spend more?compare average spend and total revenue between 
--subscribers and non-subscribers.
select subscription_status ,count(customer_id) as total_customers,
avg(purchase_amount) as avg_spend,
sum(purchase_amount) as total_revenue
from firstproj
group by subscription_status 
order by total_revenue, avg_spend desc;

--6.which 5 products have the highest percentage of purchases with discounts applied?
select top 5 item_purchased,
100*sum(case when discount_applied ='Yes' then 1
	else 0 end)/count(*)as discount_rate
from firstproj
group by item_purchased
order by discount_rate desc;

--7.segment customers into new,returning and loyal based on their total number of previous purchases and show the count of each segment.
--(asking you to divide customers into groups (segments) based on how many purchases they have made in total.)
with customer_type as (select customer_id,
previous_purchases,
case when previous_purchases=1 then 'new'
when previous_purchases between 2 and 10 then 'returning' 
else 'loyal' 
end as customer_segment
from firstproj) 

select customer_segment, count(*) as "no of customers" 
from customer_type --customer type is temporary table
group by customer_segment

--8.what are the top 3 most purchased products within each category?
with item_counts as (
select category,
item_purchased,
count(customer_id) as total_orders,
row_number() over (partition by category order by count(customer_id) desc) as item_rank
from firstproj
group by category, item_purchased)
select item_rank,category , item_purchased, total_orders
from item_counts
where item_rank<=3;

--9. are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status,
count(customer_id) as repeat_buyers
from firstproj
where previous_purchases>5 
group by subscription_status

--10.what is the revenue contribution of each age group?
select age_group,
sum(purchase_amount) as total_revenue
from firstproj
group by age_group
order by total_revenue desc;